# Android
android.useAndroidX=true
android.aapt2.useDaemon=false
android.enableJetifier=false
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false
android.enableR8.fullMode=true
android.nonFinalResIds=true

# Kotlin
kotlin.code.style=official

# Gradle JVM
org.gradle.jvmargs=-Xmx4g -Xms1g -XX:MaxMetaspaceSize=512m -XX:+UseG1GC -Dfile.encoding=UTF-8 -Djdk.lang.Process.launchMechanism=fork
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false

# KSP
ksp.incremental=true
