package com.lifelog.app.notifications

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.lifelog.app.data.db.LifeLogDatabase
import com.lifelog.app.data.db.toEntity
import com.lifelog.app.data.repository.ReminderRepository
import com.lifelog.app.domain.model.RecurrenceRule
import com.lifelog.app.domain.model.RecurrenceType
import com.lifelog.app.domain.model.Reminder
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Per-reminder contract of [ReminderCoordinator] against a real device: every transition has to
 * leave the stored row and the OS alarm agreeing with each other.
 *
 * The stored trigger is what a reboot rebuilds from, so the sharpest cases here are the ones
 * where an alarm used to be armed for a time the database never recorded (snooze) or a row
 * changed while an alarm for the old schedule stayed armed (editing into a spent rule).
 *
 * Reminder ids sit far above anything the app on this device could have created — PendingIntent
 * requestCodes are the reminder id, shared with the real app — so the test can never disturb, or
 * be fooled by, a genuinely armed reminder. An anchor row keeps autogenerated ids up there too.
 */
@RunWith(AndroidJUnit4::class)
class ReminderCoordinatorTest {

    private val context: Context = ApplicationProvider.getApplicationContext()
    private lateinit var db: LifeLogDatabase
    private lateinit var scheduler: ReminderScheduler
    private lateinit var coordinator: ReminderCoordinator

    /** Inserted in setUp so SQLite's AUTOINCREMENT hands out ids above the real app's range. */
    private val anchorId = 9_300_000L
    private val idA = 9_300_001L
    private val idB = 9_300_002L

    /** Every id whose PendingIntent this test may have created, cancelled in tearDown. */
    private val touchedIds = mutableSetOf(idA, idB)

    private val recurring = Reminder(
        title = "Recurring",
        recurrenceRule = RecurrenceRule(type = RecurrenceType.DAILY, timeOfDayMinutes = 8 * 60),
        snoozeMinutes = 15
    )

    private val oneShot = Reminder(
        title = "One-shot",
        recurrenceRule = RecurrenceRule(type = RecurrenceType.NONE, timeOfDayMinutes = 8 * 60),
        snoozeMinutes = 10
    )

    @Before
    fun setUp() {
        db = Room.inMemoryDatabaseBuilder(context, LifeLogDatabase::class.java).build()
        scheduler = ReminderScheduler(context)
        coordinator = ReminderCoordinator(
            ReminderRepository(db.reminderDao(), db.eventTypeDao()),
            scheduler
        )
        runBlocking {
            db.reminderDao().insert(recurring.copy(id = anchorId, title = "anchor").toEntity())
        }
    }

    @After
    fun tearDown() {
        touchedIds.forEach { scheduler.cancel(it) }
        db.close()
    }

    private suspend fun seed(reminder: Reminder) {
        db.reminderDao().insert(reminder.toEntity())
    }

    // ── Snooze: the deferral has to reach the database, not just AlarmManager ──

    @Test
    fun snooze_persistsTheDeferral_andABulkRearmKeepsIt() = runBlocking {
        val regularTime = System.currentTimeMillis() + 8 * HOUR
        seed(recurring.copy(id = idA, nextTriggerAt = regularTime))

        val before = System.currentTimeMillis()
        coordinator.snooze(idA)
        val after = System.currentTimeMillis()

        // Pre-fix this column still read `regularTime` — the snooze only ever reached the OS.
        val snoozed = db.reminderDao().getById(idA)!!
        assertTrue(snoozed.nextTriggerAt >= before + 15 * MINUTE)
        assertTrue(snoozed.nextTriggerAt <= after + 15 * MINUTE)
        assertTrue(scheduler.hasAlarmToken(idA))

        // What boot / timezone change / app-start recovery all run. It used to read the row back
        // and re-arm `regularTime` straight over the in-flight snooze.
        coordinator.rescheduleAll()

        assertEquals(snoozed.nextTriggerAt, db.reminderDao().getById(idA)!!.nextTriggerAt)
        assertTrue(scheduler.hasAlarmToken(idA))
    }

    @Test
    fun snooze_reactivatesAFiredOneShot_andTheDeferralSurvivesAReboot() = runBlocking {
        // Exactly the state onFired leaves a one-shot in the instant it rings: trigger elapsed,
        // row already deactivated, all before the user can reach the Snooze button.
        seed(oneShot.copy(id = idA, nextTriggerAt = System.currentTimeMillis() - 30 * MINUTE, isActive = false))

        coordinator.snooze(idA)

        val snoozed = db.reminderDao().getById(idA)!!
        assertTrue(snoozed.isActive)
        assertTrue(snoozed.nextTriggerAt > System.currentTimeMillis())
        assertTrue(scheduler.hasAlarmToken(idA))

        // A reboot re-arms from the stored trigger, and a one-shot's epoch is kept verbatim
        // (its rule holds only a time-of-day). Pre-fix that epoch was still the elapsed original,
        // so the scheduler coerced it to now+1s and the alarm went off the moment the phone booted.
        coordinator.rescheduleAll()

        val rearmed = db.reminderDao().getById(idA)!!
        assertEquals(snoozed.nextTriggerAt, rearmed.nextTriggerAt)
        assertTrue(rearmed.nextTriggerAt > System.currentTimeMillis())
    }

    // ── Editing: no alarm may outlive the schedule that armed it ──────────────

    @Test
    fun save_cancelsTheArmedAlarm_whenAnEditLeavesNothingToFire() = runBlocking {
        val original = recurring.copy(id = idA, nextTriggerAt = System.currentTimeMillis() + HOUR)
        seed(original)
        scheduler.schedule(original)
        assertTrue(scheduler.hasAlarmToken(idA))

        // Edit it into a TIME_SINCE_LAST whose countdown had already run out: there is no next
        // trigger to arm, so the editor used to simply skip scheduling — leaving the previous
        // alarm armed to ring an hour later carrying the edited title.
        coordinator.save(
            reminder = original.copy(
                title = "Edited",
                recurrenceRule = RecurrenceRule(
                    type = RecurrenceType.TIME_SINCE_LAST,
                    timeSinceLastMinutes = 60
                )
            ),
            eventDateTime = System.currentTimeMillis() - 2 * HOUR
        )

        assertFalse(scheduler.hasAlarmToken(idA))
        val saved = db.reminderDao().getById(idA)!!
        assertEquals("Edited", saved.title)
        assertEquals(RecurrenceType.TIME_SINCE_LAST.name, saved.recurrenceType)
    }

    @Test
    fun save_leavesADisabledReminderOff_andUnarmed() = runBlocking {
        seed(recurring.copy(id = idA, isActive = false))

        coordinator.save(recurring.copy(id = idA, title = "Edited", isActive = false))

        val saved = db.reminderDao().getById(idA)!!
        assertEquals("Edited", saved.title)
        // Pre-fix the editor hardcoded isActive = true, so editing a reminder the user had
        // switched off silently switched it back on and armed it.
        assertFalse(saved.isActive)
        assertFalse(scheduler.hasAlarmToken(idA))
    }

    @Test
    fun save_armsANewReminder() = runBlocking {
        val id = coordinator.save(recurring.copy(id = 0))
        touchedIds += id

        assertTrue("autogenerated id must stay clear of real reminders", id > anchorId)
        val saved = db.reminderDao().getById(id)!!
        assertTrue(saved.isActive)
        assertTrue(saved.nextTriggerAt > System.currentTimeMillis())
        assertTrue(scheduler.hasAlarmToken(id))
    }

    // ── Firing, toggling, deleting ────────────────────────────────────────────

    @Test
    fun onFired_advancesARecurringReminder_andRetiresAOneShot() = runBlocking {
        val justRang = System.currentTimeMillis()
        val ringing = recurring.copy(id = idA, nextTriggerAt = justRang)
        val spent = oneShot.copy(id = idB, nextTriggerAt = justRang)
        seed(ringing)
        seed(spent)

        coordinator.onFired(ringing)
        coordinator.onFired(spent)

        val advanced = db.reminderDao().getById(idA)!!
        assertTrue(advanced.isActive)
        assertTrue(advanced.nextTriggerAt > System.currentTimeMillis())
        assertTrue(scheduler.hasAlarmToken(idA))

        assertFalse(db.reminderDao().getById(idB)!!.isActive)
    }

    @Test
    fun setActive_cancelsTheAlarmOff_andRearmsAFutureTriggerOn() = runBlocking {
        val stored = recurring.copy(id = idA, nextTriggerAt = System.currentTimeMillis() + HOUR)
        seed(stored)
        scheduler.schedule(stored)

        coordinator.setActive(stored, isActive = false)
        assertFalse(db.reminderDao().getById(idA)!!.isActive)
        assertFalse(scheduler.hasAlarmToken(idA))

        coordinator.setActive(stored.copy(isActive = false), isActive = true)
        val reenabled = db.reminderDao().getById(idA)!!
        assertTrue(reenabled.isActive)
        assertTrue(reenabled.nextTriggerAt > System.currentTimeMillis())
        assertTrue(scheduler.hasAlarmToken(idA))
    }

    @Test
    fun delete_cancelsTheAlarmAndRemovesTheRow() = runBlocking {
        val stored = recurring.copy(id = idA, nextTriggerAt = System.currentTimeMillis() + HOUR)
        seed(stored)
        scheduler.schedule(stored)
        assertTrue(scheduler.hasAlarmToken(idA))

        coordinator.delete(idA)

        assertNull(db.reminderDao().getById(idA))
        assertFalse(scheduler.hasAlarmToken(idA))
    }

    private companion object {
        const val MINUTE = 60_000L
        const val HOUR = 60 * MINUTE
    }
}
